version: '3.8'

services:
  mysql:
    image: mysql:8.0.36-debian
    container_name: mysql-container
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
