spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/moon_project_test
    username: root
    password: kL3#9p7zXv
  flyway:
    clean-on-validation-error: true
    clean-disabled: false
    locations:
      - classpath:db/migration
      - classpath:db/fill

server:
  port: 8080
