spring:
    datasource:
        url: jdbc:mysql://localhost:3306/moon_project_test
        username: ${MYSQL_PASSWORD}
        password: ${MYSQL_USER}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
