spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/moon_project_dev
    username: root
    password: kL3#9p7zXv
  jpa:
    show-sql: true
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/fill

server:
  port: 8080
