spring:
  application:
    name: moon-project
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 10
  jpa:
    open-in-view:
      false

server:
  error:
    include-stacktrace: never
    include-message: never

jwt:
  secret: ${JWT_SECRET}
  expiration-time: 60
