INSERT INTO `roles` VALUES
  (NULL, 'ROLE_ROOT'),
  (NULL, 'ROLE_ADMIN'),
  (NULL, 'ROLE_USER'),
  (NULL, 'ROLE_LIST_USER'),
  (NULL, 'ROLE_FIND_USER'),
  (NULL, 'ROLE_REGISTER_USER'),
  (NULL, 'ROLE_UPDATE_USER'),
  (NULL, 'ROLE_DELETE_USER');
